/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PagamentoController;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Pedido;
import model.Produto;

/**
 *
 * @author Thiago
 */
public class RealizarPagamento extends javax.swing.JFrame {

    private final PagamentoController pagamentoController = new PagamentoController();
    private final NumberFormat nf = new DecimalFormat("###,##0.00");
    private final Pedido pedidoFinal;
    private final List<Produto> produtosFinal;

    public RealizarPagamento(Pedido pedido, List<Produto> produtos) {
        initComponents();
        txtCliente.setText(pedido.getCliente().getNome());
        txtIdPedido.setText(pedido.getId().toString());
        txtTotal.setText(nf.format(pedido.getValorCompra()));

        Object[] colunas = new Object[]{"Código", "Nome", "Preço R$"};
        pagamentoController.preencherTabelaProdutos(tabelaProdutos, colunas, produtos);

        pedidoFinal = pedido;
        produtosFinal = produtos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        txtCliente = new javax.swing.JLabel();
        txtIdPedido = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JToggleButton();
        radioDinheiro = new javax.swing.JRadioButton();
        radioDébito = new javax.swing.JRadioButton();
        radioCrédito = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JFormattedTextField();
        btnDesconto = new javax.swing.JButton();
        labelPagamento = new javax.swing.JLabel();
        labelPagamentoObrigatorio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cliente:");

        jLabel2.setText("Nº Pedido:");

        jLabel3.setText("Tipo de Pagamento:");

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaProdutos);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel4.setText("Valor Total:");

        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        radioDinheiro.setText("Dinheiro");
        radioDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDinheiroActionPerformed(evt);
            }
        });

        radioDébito.setText("Débito");
        radioDébito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDébitoActionPerformed(evt);
            }
        });

        radioCrédito.setText("Crédito");
        radioCrédito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCréditoActionPerformed(evt);
            }
        });

        jLabel5.setText("Desconto:");

        txtDesconto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0.00"))));

        btnDesconto.setText("Computar");
        btnDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescontoActionPerformed(evt);
            }
        });

        labelPagamento.setForeground(new java.awt.Color(255, 0, 0));
        labelPagamento.setText("*");

        labelPagamentoObrigatorio.setForeground(new java.awt.Color(255, 0, 0));
        labelPagamentoObrigatorio.setText("* Atributo Obrigatório");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPagamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCliente)
                        .addGap(167, 167, 167)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdPedido)
                        .addGap(184, 184, 184)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioDinheiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioDébito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioCrédito))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(btnFinalizar))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelPagamentoObrigatorio))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDesconto)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(txtCliente)
                            .addComponent(txtIdPedido))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(radioDinheiro)
                    .addComponent(radioDébito)
                    .addComponent(radioCrédito)
                    .addComponent(labelPagamento))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDesconto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnFinalizar)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelPagamentoObrigatorio)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        String tipo = null;
        if (Double.parseDouble(txtDesconto.getText().replace(',', '.')) < 0.00 || 
                Double.parseDouble(txtDesconto.getText().replace(',', '.')) > Double.parseDouble(txtTotal.getText().replace(',', '.'))) {
            JOptionPane.showMessageDialog(this, "Valor de desconto inválido", "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (radioDinheiro.isSelected()) {
            tipo = "0";
            pagamentoController.pagamento(this, tipo, pedidoFinal.getValorCompra(), pedidoFinal.getCliente(), pedidoFinal, pedidoFinal.getDataPedido(), produtosFinal);
        } else if (radioDébito.isSelected()) {
            tipo = "1";
            pagamentoController.pagamento(this, tipo, pedidoFinal.getValorCompra(), pedidoFinal.getCliente(), pedidoFinal, pedidoFinal.getDataPedido(), produtosFinal);
        } else if (radioCrédito.isSelected()) {
            tipo = "2";
            pagamentoController.pagamento(this, tipo, pedidoFinal.getValorCompra(), pedidoFinal.getCliente(), pedidoFinal, pedidoFinal.getDataPedido(), produtosFinal);
        } else {
            labelPagamento.setVisible(true);
            labelPagamentoObrigatorio.setVisible(true);
            JOptionPane.showMessageDialog(this, "Selecione um tipo de pagamento.", "Erro", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void radioCréditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCréditoActionPerformed
        labelPagamento.setVisible(false);
        labelPagamentoObrigatorio.setVisible(false);
        radioDinheiro.setSelected(false);
        radioDébito.setSelected(false);

    }//GEN-LAST:event_radioCréditoActionPerformed

    private void btnDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescontoActionPerformed
        txtTotal.setText(pagamentoController.computarDesconto(txtTotal, txtDesconto));
    }//GEN-LAST:event_btnDescontoActionPerformed

    private void radioDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDinheiroActionPerformed
        labelPagamento.setVisible(false);
        labelPagamentoObrigatorio.setVisible(false);
        radioCrédito.setSelected(false);
        radioDébito.setSelected(false);

    }//GEN-LAST:event_radioDinheiroActionPerformed

    private void radioDébitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDébitoActionPerformed
        labelPagamento.setVisible(false);
        labelPagamentoObrigatorio.setVisible(false);
        radioCrédito.setSelected(false);
        radioDinheiro.setSelected(false);

    }//GEN-LAST:event_radioDébitoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesconto;
    private javax.swing.JToggleButton btnFinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPagamento;
    private javax.swing.JLabel labelPagamentoObrigatorio;
    private javax.swing.JRadioButton radioCrédito;
    private javax.swing.JRadioButton radioDinheiro;
    private javax.swing.JRadioButton radioDébito;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JLabel txtCliente;
    private javax.swing.JFormattedTextField txtDesconto;
    private javax.swing.JLabel txtIdPedido;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
